backbone_variant: wan2.2
sharding_strategy: full
mixed_precision: true
seed: 0
gradient_checkpointing: true
denoising_loss_type: flow
num_train_timestep: 1000
timestep_shift: 5.0
warp_denoising_step: true
ts_schedule: false
generator_fsdp_wrap_strategy: size
text_encoder_fsdp_wrap_strategy: size
text_encoder_cpu_offload: true
wandb_host: https://api.wandb.ai
wandb_key: <your_wandb_key>
wandb_entity: <your_wandb_entity>
negative_prompt: 色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走
image_or_video_shape:
- 1
- 20
- 48
- 30
- 52
num_training_frames: 20
num_frame_per_block: 4
load_raw_video: false
data_path: ./dataset/Wan22/Control2V/data
use_camera: true
use_action: false
trainer: camera_bidirectional_diffusion
causal: false
teacher_forcing: false
guidance_scale: 8.0
lr: 2.0e-05
beta1: 0.0
beta2: 0.999
batch_size: 1
grad_accum_steps: 16
total_batch_size: 16
ema_weight: 0.99
ema_start_step: 2000000000
max_step: 500
log_iters: 500
save_iters: 50
save_trainable_only: true
wandb_project: wan22_minwm_stage0_control
model_kwargs:
  model_name: Wan2.2-TI2V-5B
  model_root: ckpts/Wan22
  timestep_shift: 5.0
  use_camera: true
  use_action: false
  lora:
    rank: 64
    alpha: 128
    train_control_params: true
text_encoder_fsdp: false
logdir: logs/astronex_stage0
ckpt_step: 0
